version: "3"

services: 
  townie-api: 
    build: .
    volumes: 
      - .:/usr/src/app
    ports:
      - "${PORT}:5000"

  townie-db:
    image: postgres:latest
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_HOST_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}

